---
# tasks file for docker-registry
- name: login into docker hub regitry
  docker_login: 
    email: "ibtissem.jenni@esprit.tn"
    username: "jenniibtissem"
    password: "23405907Jenni"
- name: tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: jenniibtissem/cd_projet1
    push: yes
    source: local
